CREATE TABLE Token(
	Token 		INT(16),
	User		VARCHAR(16),
	Expiration	TIMESTAMP,
	FOREIGN KEY(User)			REFERENCES User(Email) ON DELETE CASCADE,
	PRIMARY KEY(Token)
) ENGINE=InnoDB;

CREATE EVENT clearExpired
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 2 MINUTE
DO
   DELETE FROM Token
    WHERE Token.Expiration < NOW();