DROP TABLE TOKEN;

CREATE TABLE Token(
	Token 		INT(16),
	User		VARCHAR(100),
	Expiration	TIMESTAMP,
	FOREIGN KEY(User)			REFERENCES User(Email) ON DELETE CASCADE,
	PRIMARY KEY(Token)
) ENGINE=InnoDB;
